name: crql

on:
  push:
    branches:
      - main

jobs:
  deploy-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        run: npm install -g supabase

      - name: Login to Supabase
        run: supabase login --token $SUPABASE_ACCESS_TOKEN

      - name: Link project
        run: supabase link --project-ref $SUPABASE_PROJECT_REF

      - name: Push migrations
        run: supabase db push --include-all
